# Generated by Django 3.1.6 on 2022-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcustomer',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=10)),
                ('balance', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=10)),
                ('dt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='trans',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('sacc', models.CharField(max_length=60)),
                ('sb', models.CharField(max_length=15)),
                ('rname', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('dt', models.CharField(max_length=1000)),
            ],
        ),
    ]
