# Generated by Django 3.1.6 on 2022-02-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSFbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trans',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
