# Generated by Django 3.1.6 on 2022-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSFbank', '0002_auto_20220207_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
